//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeiaMeg.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeiaMeg.Resources.AppText", typeof(AppText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appen er levert av.
        /// </summary>
        internal static string about_final_text {
            get {
                return ResourceManager.GetString("about_final_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det er mange som mener noe om hva nettopp DU bør ta tak i, men du har sikkert kjent at velmente formaninger ikke akkurat tenner gnisten i deg? En forutsetning for å lykkes med endringer er at det kommer innenfra – at du virkelig kjenner at dette er noe DU vil. Bare du kan starte endringer i ditt eget liv. Heia meg-appen er ditt daglige heiarop. 
        ///
        ///Når du har lasta ned appen velger du hva DU vil ta tak i. Så får du en melding hver dag som minner deg på det du har bestemt deg for og gir deg litt ekstra kreft [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string about_text {
            get {
                return ResourceManager.GetString("about_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om appen.
        /// </summary>
        internal static string about_title {
            get {
                return ResourceManager.GetString("about_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meldinger.
        /// </summary>
        internal static string tab_archive {
            get {
                return ResourceManager.GetString("tab_archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meldinger.
        /// </summary>
        internal static string tab_archive_title {
            get {
                return ResourceManager.GetString("tab_archive_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favoritter.
        /// </summary>
        internal static string tab_favorites {
            get {
                return ResourceManager.GetString("tab_favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dine favoritter.
        /// </summary>
        internal static string tab_favorites_title {
            get {
                return ResourceManager.GetString("tab_favorites_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nye.
        /// </summary>
        internal static string tab_new {
            get {
                return ResourceManager.GetString("tab_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nye meldinger.
        /// </summary>
        internal static string tab_new_title {
            get {
                return ResourceManager.GetString("tab_new_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string tab_settings {
            get {
                return ResourceManager.GetString("tab_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string tab_settings_title {
            get {
                return ResourceManager.GetString("tab_settings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helsedirektoratet
        ///Vitaminveien 4
        ///0485 Oslo.
        /// </summary>
        internal static string terms_1_0_text {
            get {
                return ResourceManager.GetString("terms_1_0_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App-eier (dataeier).
        /// </summary>
        internal static string terms_1_0_title {
            get {
                return ResourceManager.GetString("terms_1_0_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heia meg baserer seg på brukernes valg av temaer de ønsker å følge. På bakgrunn av disse valgene vil appen automatisk sende deg råd og motivasjon om tema du har valgt..
        /// </summary>
        internal static string terms_2_0_text {
            get {
                return ResourceManager.GetString("terms_2_0_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualisering av dine data.
        /// </summary>
        internal static string terms_2_0_title {
            get {
                return ResourceManager.GetString("terms_2_0_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Som de fleste nettsider og apper har vi informasjonskapsler plassert i appen. Formålet med disse er å kunne gi en bedre brukeropplevelse basert på hvordan appen brukes. Vi sparer ikke på andre data enn det bruker selv har gitt (fornavn). Det er ingen personlige data lagret i appen.
        ///I tillegg benytter vi informasjonskapsler for å effektivisere annonseringen av appen og måle hvor brukeren kommer fra.
        ///Data blir ikke delt med andre tredjepartsaktører utover det vi beskriver under..
        /// </summary>
        internal static string terms_3_0_text {
            get {
                return ResourceManager.GetString("terms_3_0_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informasjonskapsler.
        /// </summary>
        internal static string terms_3_0_title {
            get {
                return ResourceManager.GetString("terms_3_0_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi benytter AppCenter (https://appcenter.ms) for å måle hvilke deler av appen som brukes. Vi bruker denne innsikten til å oppgradere appen for å gi brukeren et bedre verktøy..
        /// </summary>
        internal static string terms_3_1_text {
            get {
                return ResourceManager.GetString("terms_3_1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppCenter.
        /// </summary>
        internal static string terms_3_1_title {
            get {
                return ResourceManager.GetString("terms_3_1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adform (https://www.adform.com) er et annonsestyringsverktøy vi bruker for å promotere appen og som gir oss innsikt i hvor brukeren kommer fra..
        /// </summary>
        internal static string terms_3_2_text {
            get {
                return ResourceManager.GetString("terms_3_2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adform.
        /// </summary>
        internal static string terms_3_2_title {
            get {
                return ResourceManager.GetString("terms_3_2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi promoterer appen gjennom Facebook. På samme måte som Adform gir Facebook analytics oss innsikt i bruken og nedlasting av appen (https://facebook.com/about/privacy)..
        /// </summary>
        internal static string terms_3_3_text {
            get {
                return ResourceManager.GetString("terms_3_3_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook analytics.
        /// </summary>
        internal static string terms_3_3_title {
            get {
                return ResourceManager.GetString("terms_3_3_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det beste for helsa er å begrense alkoholinntaket. Det betyr å begrense antall glass ved de anledningene du drikker – og å sørge for at uka har flest &quot;hvite&quot; dager. Det beste du kan gjøre er å lage dine egne &quot;drikkeregler&quot; – som for eksempel &quot;vann på hverdager&quot;..
        /// </summary>
        internal static string theme_alcohol_description {
            get {
                return ResourceManager.GetString("theme_alcohol_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alkohol.
        /// </summary>
        internal static string theme_alcohol_name {
            get {
                return ResourceManager.GetString("theme_alcohol_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drikke mindre alkohol.
        /// </summary>
        internal static string theme_alcohol_title {
            get {
                return ResourceManager.GetString("theme_alcohol_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to God planlegging er halve jobben. Lag en ukemeny, ta med handleliste i butikken og ha med matpakke på farten. Da unngår du spontane mellommåltider og er bedre rustet når du har mindre viljestyrke..
        /// </summary>
        internal static string theme_diet_description {
            get {
                return ResourceManager.GetString("theme_diet_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosthold.
        /// </summary>
        internal static string theme_diet_name {
            get {
                return ResourceManager.GetString("theme_diet_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Få et sunnere kosthold.
        /// </summary>
        internal static string theme_diet_title {
            get {
                return ResourceManager.GetString("theme_diet_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faste rutiner er din beste venn – da slipper du å bruke energi på å finne motivasjon hver gang. Bygg rutiner over noen uker – så går det etter hvert på autopilot. Og husk at ALT er bedre enn ingenting!.
        /// </summary>
        internal static string theme_exercise_description {
            get {
                return ResourceManager.GetString("theme_exercise_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fysisk Aktivitet.
        /// </summary>
        internal static string theme_exercise_name {
            get {
                return ResourceManager.GetString("theme_exercise_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komme i bedre form.
        /// </summary>
        internal static string theme_exercise_title {
            get {
                return ResourceManager.GetString("theme_exercise_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle har tunge perioder, men fem grep kan gjøre deg mer robust når de litt blå dagene kommer. Meldingene vil minne deg på å knytte bånd til andre, være aktiv, være oppmerksom, fortsette å lære og å gi til andre..
        /// </summary>
        internal static string theme_mentality_description {
            get {
                return ResourceManager.GetString("theme_mentality_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psykisk Helse.
        /// </summary>
        internal static string theme_mentality_name {
            get {
                return ResourceManager.GetString("theme_mentality_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bli sterkere psykisk.
        /// </summary>
        internal static string theme_mentality_title {
            get {
                return ResourceManager.GetString("theme_mentality_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De aller fleste har problemer med å sove innimellom, men ikke alle tar tak for å gjøre endringer som kan gi bedre søvn..
        /// </summary>
        internal static string theme_sleep_description {
            get {
                return ResourceManager.GetString("theme_sleep_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søvn.
        /// </summary>
        internal static string theme_sleep_name {
            get {
                return ResourceManager.GetString("theme_sleep_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Få bedre søvnvaner.
        /// </summary>
        internal static string theme_sleep_title {
            get {
                return ResourceManager.GetString("theme_sleep_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Å stumpe røyken er kanskje det aller beste du kan gjøre for helsa di. Du bør være forberedt på at de første dagene blir vanskelig – så blir det gradvis lettere etter hvert. Legg til rette for å lykkes – sørg for å ha aktiviteter eller noe å tygge på som avleder deg om du har røyksug..
        /// </summary>
        internal static string theme_smoking_description {
            get {
                return ResourceManager.GetString("theme_smoking_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tobakk.
        /// </summary>
        internal static string theme_smoking_name {
            get {
                return ResourceManager.GetString("theme_smoking_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slutte med røyk.
        /// </summary>
        internal static string theme_smoking_title {
            get {
                return ResourceManager.GetString("theme_smoking_title", resourceCulture);
            }
        }
    }
}
